### ISSUE TITLE
[BUG] It takes a lot of time to execute, especially `tailwindcss/classnames-order `

### ISSUE THREAD

**Issue by ronny1020** [francoismassart/eslint-plugin-tailwindcss#136]
**Describe the bug**
It takes a lot of time to execute `Eslint`.
And I use `TIMING=1` to find the reason.
here is what I get
```bash
Rule                                   | Time (ms) | Relative
:--------------------------------------|----------:|--------:
tailwindcss/classnames-order           | 10097.373 |    50.0%
prettier/prettier                      |  2399.615 |    11.9%
tailwindcss/enforces-shorthand         |  2330.436 |    11.5%
import/no-cycle                        |  1044.403 |     5.2%
import/no-relative-packages            |   455.328 |     2.3%
import/order                           |   397.291 |     2.0%
tailwindcss/no-custom-classname        |   264.854 |     1.3%
import/no-extraneous-dependencies      |   257.201 |     1.3%
import/extensions                      |   253.208 |     1.3%
tailwindcss/no-contradicting-classname |   179.790 |     0.9%
```

It takes almost half of the time to run `tailwindcss/classnames-order` and about 10% of the time to run `ailwindcss/enforces-shorthand `

**To Reproduce**
1. On the terminal, run `TIMING=1 npx eslint src`
2. check the result

**Expected behavior**
I think the time sould not take so much.

**Environment (please complete the following information):**
 - OS: macOS 12.3.1
 - Softwares + version used:
 - node v16.14.0
 - npm v8.3.1

**Additional context**

**eslint config file or live demo**
```js
{
    // ...
   "tailwindcss": {
      "callees": ["joinClassNames"],
      "config": "tailwind.config.js",
      "cssFiles": ["**/*.css"]
    }
}

```

**Comment by francoismassart** [comment]
Hi @ronny1020,
Parsing the css files is not very fast, can you use a narrower glob pattern than **/*.css for the cssFiles option ?
Also, I believe you need to avoid parsing the main css file generated by Tailwind CSS 🔁

Can you try this? Make sure to reboot your IDE too after editing the option, just to be sure. 

If you need help for the glob pattern(s) please share the files/folders structure. 

Let me know if it works 🥸

**Comment by ronny1020** [comment]
I only have one CSS file under src, which is `src/index.css`. It's just a small file. 
I just tried `{..., "cssFiles": ["src/index.css" ]}`. Actually, I do feel it's a little bit faster. However, The result is similar.

```bash
Rule                                   | Time (ms) | Relative
:--------------------------------------|----------:|--------:
tailwindcss/classnames-order           | 10251.320 |    51.3%
prettier/prettier                      |  2327.852 |    11.6%
tailwindcss/enforces-shorthand         |  2271.232 |    11.4%
import/no-cycle                        |   993.849 |     5.0%
import/no-relative-packages            |   457.439 |     2.3%
import/order                           |   359.858 |     1.8%
import/no-extraneous-dependencies      |   275.121 |     1.4%
import/extensions                      |   247.653 |     1.2%
tailwindcss/no-custom-classname        |   196.434 |     1.0%
tailwindcss/no-contradicting-classname |   165.654 |     0.8%
```

**Comment by francoismassart** [comment]
Questions:

- Could you share the content of that CSS files ?
- What IDE are you using ? VSCode ?
- Which version of `eslint-plugin-tailwindcss` are you on ?

Thanks

**Comment by ronny1020** [comment]
Thanks for your reply.

- Here is the content of the `src/index.css` file.

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  font-size: 12.8px;
}

@layer utilities {
  /* Hide arrows on number input for Chrome, Safari, Edge, Opera */
  input[type='number']::-webkit-inner-spin-button,
  input[type='number']::-webkit-outer-spin-button {
    -webkit-appearance: none;
    margin: 0;
  }

  /* Hide arrows on number input for Firefox */
  input[type='number'] {
    -moz-appearance: textfield;
  }
}
```

- I use Vscode, the version is `1.66.2`. The `TIMING=1 npx eslint src` is run on `zsh`, which version is `5.8`.

- the version of `eslint-plugin-tailwindcss` is `3.5.0`, and the version of `tailwindcss` is `3.0.7`
