### ISSUE TITLE
`eslint-plugin-tailwindcss` should include `tailwindcss` as a (peer)dependency in `package.json`

### ISSUE THREAD

**Issue by lensbart** [francoismassart/eslint-plugin-tailwindcss#230]
When running `eslint-plugin-tailwindcss` in a project that uses [Yarn PnP](https://yarnpkg.com/features/pnp), the ESLint process fails with the following error:

```
Failed to load plugin 'eslint-plugin-tailwindcss' declared in '.eslintrc.js#overrides[4]': eslint-plugin-tailwindcss tried to access tailwindcss, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

An easy workaround is to include the following in the root `.yarnrc.yml`:
```yml
# .yarnrc.yml
packageExtensions:
  # awaiting fix: https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/230
  eslint-plugin-tailwindcss@*:
    dependencies:
      tailwindcss: '*'
```

and running `yarn` again. But a better solution would be to include `tailwindcss ` as a dependency in the `package.json` of `eslint-plugin-tailwindcss`

Using `eslint-plugin-tailwindcss` v3.10.3

Thank you!
