### ISSUE TITLE
[BUG] SyntaxError: Invalid regular expression when parsing CSS

### ISSUE THREAD

**Issue by thebuilder** [francoismassart/eslint-plugin-tailwindcss#35]
Seeing an error when the plugin tries to parse our CSS files. It constructs an invalid regular expression because of the `[]`.

```
SyntaxError: Invalid regular expression: /^(focus-outline[data-focus-visible-added])$/: Range out of order in character class
Occurred while linting /src/components/Button/Button.tsx:56
    at new RegExp (<anonymous>)
    at String.<anonymous> (/node_modules/eslint-plugin-tailwindcss/lib/util/groupMethods.js:170:21)
```

The css in question is located in a `.css` file, with:

```css
/* override input always getting focus styling from package "focus-visible" */
.focus-outline[data-focus-visible-added].focus-visible.focus,
.focus-outline[data-focus-visible-added].focus-visible.focus:focus,
input[type='text'].focus\:outline-none[data-focus-visible-added]:focus,
input[type='email'].focus\:outline-none[data-focus-visible-added]:focus {
  box-shadow: none;
  outline-width: 0;
}
```

The `groupMethods.js` should sanitize the string before creating the Regex. 

```js
new RegExp(test.replace(/[#-}]/g, '\\$&'));
```

https://stackoverflow.com/questions/6300183/sanitize-string-of-regex-characters-before-regexp-build
